backend/blueprints/admin.py
import time
from urllib.parse import urlparse, urljoin
from bson import ObjectId
from flask import Blueprint, render_template, request, redirect, session, url_for, flash
from flask import current_app as app
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, current_user, logout_user
from utils.user import User


admin_blueprint = Blueprint(
    "admin", __name__)


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and \
        ref_url.netloc == test_url.netloc


def get_incidents_by_id(component_id):
    component_id = str(component_id)
    incidents = app.database.incidents.find(
        {"affected_services": component_id})
    result = []
    for incident in incidents:
        if 'closed_at' in incident:
            continue
        incident["id"] = str(incident.pop("_id"))
        incident.pop("affected_services")
        result.append(incident)
    return result


def _get_incidents():
    incidents = []
    for incident in app.database.incidents.find():
        incident["id"] = str(incident.pop("_id"))
        incident['active'] = "closed_at" not in incident
        services = []
        for service in incident['affected_services']:
            s = app.database.components.find_one({"_id": ObjectId(service)})
            if s:
                services.append({"id": service, "name": s['name']})
        if len(services) != len(incident['affected_services']):
            app.database.components.update_one({"_id": ObjectId(service)}, {
                                               "$set": {"affected_services": [x['id'] for x in services]}})
        incident['services'] = services
        severity = incident['severity']
        status = {"status": "operational", "name": "Operational"}
        if severity in ['partial']:
            status = {"status": "partial",
                      "name": "Partial Outage"}
        if severity in ['major']:
            status = {"status": "major", "name": "Major Outage"}
        incident['status'] = status
        incidents.append(incident)
    return {
        "data": incidents,
        "metadata": {
            "amount": len(incidents),
            "active": len([x for x in incidents if x['active']])
        }
    }


def _get_components():
    components = []
    for component in app.database.components.find():
        status = {"status": "operational",
                  "name": "Operational"}
        component["id"] = str(component.pop("_id"))
        components.append(component)
        active_incidents = get_incidents_by_id(component['id'])
        statuses = [incident['severity']
                    for incident in active_incidents]
        if "partial" in statuses:
            status = {"status": "partial",
                      "name": "Partial Outage"}
        if "major" in statuses:
            status = {"status": "major", "name": "Major Outage"}
        component['status'] = status
        component['incidents'] = {"metadata": {
            "amount": len(active_incidents)}, "data": active_incidents}
    return {
        "data": components,
        "metadata": {
            "amount": len(components),
            "active": len([x for x in components if x['status']['status'] != "operational"])
        }
    }


@admin_blueprint.route("/")
@login_required
def homepage():
    return render_template("index.html", incidents=_get_incidents(), components=_get_components())


@admin_blueprint.route("/components")
@login_required
def get_components():
    return render_template("components/list.html", components=_get_components())


@admin_blueprint.route("/components/create", methods=['GET'])
@login_required
def get_create_component():
    return render_template("/components/create.html")


@admin_blueprint.route("/components/<component>/delete", methods=['POST'])
@login_required
def post_delete_component(component):
    if ObjectId.is_valid(component):
        app.database.components.delete_one({"_id": ObjectId(component)})
    return redirect(url_for("admin.get_components"))


@admin_blueprint.route("/components/<component>/delete", methods=['get'])
@login_required
def get_delete_component(component):
    if not ObjectId.is_valid(component):
        return redirect(url_for("admin.get_components"))
    component_object = app.database.components.find_one(
        {"_id": ObjectId(component)})
    if not component_object:
        return redirect(url_for("admin.get_components"))
    component_object['id'] = str(component_object.pop("_id"))
    return render_template("/components/delete_confirm.html", component=component_object)


@admin_blueprint.route("/incidents/<incident>/delete", methods=['POST'])
@login_required
def post_delete_incident(incident):
    if ObjectId.is_valid(incident):
        app.database.incidents.delete_one({"_id": ObjectId(incident)})
    return redirect(url_for("admin.get_incidents"))


@admin_blueprint.route("/incidents/<incident>/delete", methods=['get'])
@login_required
def get_delete_incident(incident):
    if not ObjectId.is_valid(incident):
        return redirect(url_for("admin.get_incidents"))
    incident_object = app.database.incidents.find_one(
        {"_id": ObjectId(incident)})
    if not incident_object:
        return redirect(url_for("admin.get_incidents"))
    incident_object['id'] = str(incident_object.pop("_id"))
    return render_template("/incidents/delete_confirm.html", incident=incident_object)


@admin_blueprint.route("/components/create", methods=['POST'])
@login_required
def post_create_component():
    name = request.form['name'].strip()
    if not name:
        flash("Name must not be blank", "danger")
        return render_template("/components/create.html")
    component = app.database.components.find_one({"name": name})
    if component:
        flash("A component with that name already exists", "danger")
        return render_template("/components/create.html")
    component_id = app.database.components.insert_one(
        {"name": name}).inserted_id
    return redirect(url_for("admin.get_component_by_id", component=str(component_id)))


def get_components_basic():
    components = []
    for component in app.database.components.find():
        components.append(
            {"name": component['name'], 'id': str(component['_id'])})
    return components


@admin_blueprint.route("/incidents/create", methods=['GET'])
@login_required
def get_create_incident():
    return render_template("/incidents/create.html", components=get_components_basic())


@admin_blueprint.route("/incidents/create", methods=['POST'])
@login_required
def post_create_incident():
    components = [arg.split(
        ".")[1] for arg in request.form if arg.startswith("components.")]
    if request.form['title'] == "":
        flash("Name must not be blank", "danger")
        return redirect(url_for('admin.get_create_incident'))
    if len(components) < 1:
        flash("You must select at least one component", "danger")
        return redirect(url_for('admin.get_create_incident'))
    data = {"affected_services": components,
            "title": request.form['title'], "severity": request.form['severity'], "created_at": int(time.time(
            ))*1000}

    incident_id = app.database.incidents.insert_one(
        data).inserted_id
    return redirect(url_for("admin.get_incident_by_id", incident=str(incident_id)))


@admin_blueprint.route("/incidents/<incident>")
@login_required
def get_incident_by_id(incident):
    if not ObjectId.is_valid(incident):
        return redirect(url_for("admin.get_incidents"))
    incident_object = app.database.incidents.find_one(
        {"_id": ObjectId(incident)})
    if not incident_object:
        return redirect(url_for("admin.get_incidents"))
    incident_object['id'] = str(incident_object.pop("_id"))
    return render_template("incidents/view.html", incident=incident_object, components=get_components_basic())


@admin_blueprint.route("/incidents/<incident>/open")
@login_required
def open_incident_by_id(incident):
    if not ObjectId.is_valid(incident):
        return redirect(url_for("admin.get_incidents"))
    incident_object = app.database.incidents.find_one(
        {"_id": ObjectId(incident)})
    if not incident_object:
        return redirect(url_for("admin.get_incidents"))
    app.database.incidents.update_one({"_id": ObjectId(incident)}, {
        "$unset": {"closed_at": None}})
    flash("The incident has been reopened", "success")
    return redirect(url_for('admin.get_incident_by_id', incident=incident))


@admin_blueprint.route("/incidents/<incident>/close")
@login_required
def close_incident_by_id(incident):
    if not ObjectId.is_valid(incident):
        return redirect(url_for("admin.get_incidents"))
    incident_object = app.database.incidents.find_one(
        {"_id": ObjectId(incident)})
    if not incident_object:
        return redirect(url_for("admin.get_incidents"))
    app.database.incidents.update_one({"_id": ObjectId(incident)}, {
        "$set": {"closed_at": int(time.time(
        ))*1000}})
    flash("The incident has been closed", "success")
    return redirect(url_for('admin.get_incident_by_id', incident=incident))


@admin_blueprint.route("/users/<user>/delete", methods=['POST'])
@login_required
def post_delete_user(user):
    if ObjectId.is_valid(user):
        app.database.users.delete_one({"_id": ObjectId(user)})
    return redirect(url_for("admin.get_users"))


@admin_blueprint.route("/users/<user>/delete", methods=['get'])
@login_required
def get_delete_user(user):
    if not ObjectId.is_valid(user):
        return redirect(url_for("admin.get_users"))
    user_object = app.database.users.find_one(
        {"_id": ObjectId(user)})
    if not user_object:
        return redirect(url_for("admin.get_users"))
    user_object['id'] = str(user_object.pop("_id"))

backend/templates/incidents/create.html
{% extends "layout.html" %}
{% block title %}
Incidents > Create
{% endblock %}
{% block content %}

<div class="page">
    <div class="container py-4">
        <div class="card">
            <div class="card-body">
                {% with errors = get_flashed_messages(category_filter=["danger"]) %}
                {% if errors %}
                {%- for message in errors %}

                <div class="alert alert-danger" role="alert">
                    <h4 class="alert-title">Error</h4>
                    <div class="text-muted">{{ message }}</div>
                </div>
                {% endfor -%}
                {% endif %}
                {% endwith %}
                <form method="post" id="form">
                    <h3 class="card-title mt-4">General Information</h3>
                    <div class="row g-3">
                        <div class="col-md">
                            <div class="form-label">Incident Name</div>
                            <input type="text" name="title" class="form-control">
                        </div>
                        <div class="mb-3">
                            <div class="form-label">Severity</div>
                            <select class="form-select" name="severity" {% if 'closed_at' in incident %}disabled{% endif
                                %}>
                                <option value="major">Major Outage
                                </option>
                                <option value="partial">Partial
                                    Outage</option>
                                <option value="issues">Issues
                                </option>
                            </select>
                        </div>
                    </div>
                    <div class="card-body">
                        <h3 class="card-title mt-4">Affected Services</h3>
                        <div class="row g-3">

                            <div class="form-label">Checkboxes</div>
                            <div>
                                {% for component in components %}
                                <label class="form-check">
                                    <input class="form-check-input" name="components.{{component['id']}}"
                                        type="checkbox">
                                    <span class="form-check-label">{{component.name}}</span>
                                </label>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="form-footer">
                        <button type="submit" class="btn btn-primary w-100">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {% endblock %}

backend/templates/incidents/delete_confirm.html
{% extends "layout.html" %}
{% block title %}
Incidents > {{incident.title}} > Delete
{% endblock %}
{% block content %}
<div class="page-body">
    <div class="container-xl">
        <div class="card">
            <div class="row g-0">
                <div class="col d-flex flex-column">
                    <form method="post" id="form">
                        <div class="card-body">
                            <h2 class="mb-4">Are you sure you want to delete incident "{{incident.title}}"?</h2>
                            <h3 class="card-title mt-4">This action cannot be reverted</h3>
                        </div>
                        <div class="card-footer bg-transparent mt-auto">
                            <div class="btn-list justify-content-start">
                                <a onclick='document.getElementById("form").submit()' class="btn btn-danger">
                                    Delete
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

backend/templates/incidents/list.html
{% extends "layout.html" %}
{% block title %}
Incidents
{% endblock %}
{% block content %}
<div class="page-body">
    <div class="container-xl">
        <div class="card">
            <div class="card-body">
                <div id="table-default" class="table-responsive">
                    <a href="{{url_for('admin.get_create_incident')}}" class="btn btn-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-plus" width="24"
                            height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                            stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M12 5l0 14"></path>
                            <path d="M5 12l14 0"></path>
                        </svg>Create New</a>
                    <table class="table">
                        <thead>
                            <tr>
                                <th><button class="table-sort" data-sort="sort-title">Title</button></th>
                                <th><button class="table-sort" data-sort="sort-status">Severity</button></th>
                                <th><button class="table-sort" data-sort="sort-affected">Affected Services</button></th>
                            </tr>
                        </thead>
                        <tbody class="table-tbody">
                            {% for incident in incidents['data'] %}

                            <tr>
                                <td class="sort-title"><a class="link-secondary" style="color:white"
                                        href="{{url_for('admin.get_incident_by_id', incident=incident['id'])}}">{{incident['title']}}</a>
                                </td>
                                <td class="sort-severity">{{incident['status']['name']}}</td>
                                <td class="sort-affected">
                                    {% for service in incident['services'] %}
                                    {{service['name']}}<br>
                                    {% endfor %}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

backend/templates/incidents/view.html
{% extends "layout.html" %}
{% block title %}
Incidents > {{incident.title}}
{% endblock %}
{% block content %}
<div class="page-body">
    <div class="container-xl">
        <div class="card">
            <div class="row g-0">
                <div class="col d-flex flex-column">

                    <form method="post" id="form">
                        <div class="card-body">
                            {% with errors = get_flashed_messages(category_filter=["danger"]) %}
                            {% if errors %}
                            {%- for message in errors %}

                            <div class="alert alert-danger" role="alert">
                                <h4 class="alert-title">Error</h4>
                                <div class="text-muted">{{ message }}</div>
                            </div>
                            {% endfor -%}
                            {% endif %}
                            {% endwith %}
                            {% with successes = get_flashed_messages(category_filter=["success"]) %}
                            {% if successes %}
                            {%- for message in successes %}

                            <div class="alert alert-success" role="alert">
                                <h4 class="alert-title">Success</h4>
                                <div class="text-muted">{{ message }}</div>
                            </div>
                            {% endfor -%}
                            {% endif %}
                            {% endwith %}
                            <h2 class="mb-4">Manage Incident</h2>
                            <h3 class="card-title mt-4">General Information</h3>
                            <div class="row g-3">
                                <div class="col-md">
                                    <div class="form-label">Incident Name</div>
                                    <input type="text" name="title" class="form-control" value="{{incident.title}}" {%
                                        if 'closed_at' in incident %}disabled{% endif %}>
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Severity</div>
                                    <select class="form-select" name="severity" {% if 'closed_at' in incident
                                        %}disabled{% endif %}>
                                        <option value="major" {% if 'closed_at' in incident %}disabled{% endif %} {% if
                                            incident['severity']=='major' %}selected="selected" {% endif %}>Major Outage
                                        </option>
                                        <option value="partial" {% if 'closed_at' in incident %}disabled{% endif %} {%
                                            if incident['severity']=='partial' %}selected="selected" {% endif %}>Partial
                                            Outage</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <h3 class="card-title mt-4">Affected Services</h3>
                            <div class="row g-3">

                                <div class="form-label">Checkboxes</div>
                                <div>
                                    {% for component in components %}
                                    <label class="form-check">
                                        <input class="form-check-input" name="components.{{component['id']}}"
                                            type="checkbox" {% if 'closed_at' in incident %}disabled{% endif %} {% if
                                            component['id'] in incident['affected_services'] %} checked{% endif%}>
                                        <span class="form-check-label">{{component.name}}</span>
                                    </label>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="card-footer bg-transparent mt-auto">
                            <div class="btn-list justify-content-end">
                                <a href="{{url_for('admin.get_incidents')}}" class="btn">
                                    Cancel
                                </a>
                                {% if 'closed_at' in incident %}
                                <a href="{{url_for('admin.open_incident_by_id', incident=incident['id'])}}"
                                    class="btn btn-primary">
                                    Reopen
                                </a>
                                {% else %}
                                <a onclick='document.getElementById("form").submit()' class="btn btn-primary">
                                    Update
                                </a>
                                <a href="{{url_for('admin.close_incident_by_id', incident=incident['id'])}}"
                                    class="btn btn-success">
                                    Close
                                </a>
                                {% endif %}
                                <a href="{{url_for('admin.get_delete_incident', incident=incident['id'])}}"
                                    class="btn btn-danger">
                                    Delete
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}